# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatTemplateInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='\u72b6\u6001', verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4', verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\u66f4\u65b0\u65f6\u95f4', verbose_name='updated_at')),
                ('wepush_id', shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, help_text='\u6a21\u677f\u552f\u4e00\u6807\u8bc6', max_length=22, unique=True)),
                ('wepush_secret', shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, help_text='\u6a21\u677f\u6d88\u606f\u5bc6\u94a5', max_length=22)),
                ('app_id', models.CharField(db_index=True, help_text='\u5f00\u53d1\u8005ID', max_length=255, verbose_name='app_id')),
                ('app_secret', models.CharField(db_index=True, help_text='\u5f00\u53d1\u8005\u5bc6\u94a5', max_length=255, verbose_name='app_secret')),
                ('template_id', models.CharField(db_index=True, help_text='\u6a21\u677fID', max_length=255, verbose_name='template_id')),
            ],
            options={
                'verbose_name': 'wechattemplateinfo',
                'verbose_name_plural': 'wechattemplateinfo',
            },
        ),
        migrations.CreateModel(
            name='WeChatTemplateMessageRequestLogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='\u72b6\u6001', verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4', verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\u66f4\u65b0\u65f6\u95f4', verbose_name='updated_at')),
                ('request_id', shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, help_text='\u8bf7\u6c42\u552f\u4e00\u6807\u8bc6', max_length=22, unique=True)),
                ('wepush_id', models.CharField(db_index=True, help_text='\u6a21\u677f\u552f\u4e00\u6807\u8bc6', max_length=255, verbose_name='wepush_id')),
                ('request_ip', models.CharField(blank=True, help_text='\u8bf7\u6c42IP', max_length=255, null=True, verbose_name='request_ip')),
                ('request_text', models.TextField(blank=True, help_text='\u8bf7\u6c42\u6587\u672c', null=True, verbose_name='request_text')),
                ('request_sign_status', models.BooleanField(default=True, help_text='\u8bf7\u6c42\u7b7e\u540d\u72b6\u6001', verbose_name='request_sign_status')),
            ],
            options={
                'verbose_name': 'wechattemplatemessagerequestloginfo',
                'verbose_name_plural': 'wechattemplatemessagerequestloginfo',
            },
        ),
        migrations.CreateModel(
            name='WeChatTemplateMessageSendLogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='\u72b6\u6001', verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4', verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\u66f4\u65b0\u65f6\u95f4', verbose_name='updated_at')),
                ('send_id', shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, help_text='\u53d1\u9001\u552f\u4e00\u6807\u8bc6', max_length=22, unique=True)),
                ('wepush_id', models.CharField(db_index=True, help_text='\u6a21\u677f\u552f\u4e00\u6807\u8bc6', max_length=255, verbose_name='wepush_id')),
                ('openid', models.CharField(blank=True, db_index=True, help_text='\u63a5\u53d7\u8005Openid', max_length=255, null=True, verbose_name='openid')),
                ('send_status', models.BooleanField(default=True, help_text='\u53d1\u9001\u72b6\u6001', verbose_name='send_status')),
            ],
            options={
                'verbose_name': 'wechattemplatemessagesendloginfo',
                'verbose_name_plural': 'wechattemplatemessagesendloginfo',
            },
        ),
        migrations.CreateModel(
            name='WeChatTemplateReceiverInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(db_index=True, default=True, help_text='\u72b6\u6001', verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='\u521b\u5efa\u65f6\u95f4', verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='\u66f4\u65b0\u65f6\u95f4', verbose_name='updated_at')),
                ('receiver_id', shortuuidfield.fields.ShortUUIDField(blank=True, db_index=True, editable=False, help_text='\u63a5\u6536\u4eba\u552f\u4e00\u6807\u8bc6', max_length=22, unique=True)),
                ('wepush_id', models.CharField(db_index=True, help_text='\u6a21\u677f\u552f\u4e00\u6807\u8bc6', max_length=255, verbose_name='wepush_id')),
                ('openid', models.CharField(blank=True, db_index=True, help_text='\u63a5\u53d7\u8005Openid', max_length=255, null=True, verbose_name='openid')),
            ],
            options={
                'verbose_name': 'wechattemplatereceiverinfo',
                'verbose_name_plural': 'wechattemplatereceiverinfo',
            },
        ),
    ]
