# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepush', '0002_wechattemplatemessagesendloginfo_send_msgres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechattemplatemessagerequestloginfo',
            name='request_ip',
            field=models.GenericIPAddressField(blank=True, help_text='\u8bf7\u6c42IP', null=True, verbose_name='request_ip'),
        ),
        migrations.AlterField(
            model_name='wechattemplatemessagerequestloginfo',
            name='wepush_id',
            field=models.CharField(db_index=True, help_text='\u6a21\u677f\u552f\u4e00\u6807\u8bc6', max_length=32, verbose_name='wepush_id'),
        ),
        migrations.AlterField(
            model_name='wechattemplatemessagesendloginfo',
            name='wepush_id',
            field=models.CharField(db_index=True, help_text='\u6a21\u677f\u552f\u4e00\u6807\u8bc6', max_length=32, verbose_name='wepush_id'),
        ),
        migrations.AlterField(
            model_name='wechattemplatereceiverinfo',
            name='wepush_id',
            field=models.CharField(db_index=True, help_text='\u6a21\u677f\u552f\u4e00\u6807\u8bc6', max_length=32, verbose_name='wepush_id'),
        ),
    ]
