# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepush', '0003_auto_20171105_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechattemplateinfo',
            name='token_url',
            field=models.URLField(blank=True, help_text='\u83b7\u53d6access_token\u94fe\u63a5', null=True, verbose_name='token_url'),
        ),
    ]
