# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepush', '0004_wechattemplateinfo_token_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechattemplateinfo',
            name='token_key',
            field=models.CharField(blank=True, help_text='access_token key', max_length=255, null=True, verbose_name='token_key'),
        ),
    ]
