# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepush', '0006_wechattemplateinfo_wepush_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechattemplateinfo',
            name='wepush_remark',
            field=models.CharField(blank=True, help_text='\u6a21\u677f\u6d88\u606f\u5907\u6ce8', max_length=32, null=True, verbose_name='wepush_remark'),
        ),
    ]
