# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-25 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepush', '0007_auto_20171125_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechattemplatereceiverinfo',
            name='receiver_remark',
            field=models.CharField(blank=True, help_text='\u63a5\u6536\u4eba\u5907\u6ce8', max_length=32, null=True, verbose_name='receiver_remark'),
        ),
    ]
