# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wepush', '0009_auto_20180119_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='wechattemplatemessagesendloginfo',
            name='request_id',
            field=models.CharField(blank=True, db_index=True, help_text='\u8bf7\u6c42\u552f\u4e00\u6807\u8bc6', max_length=32, null=True, verbose_name='request_id'),
        ),
    ]
